Feature: General Test of Twitter application
  This Feature tests the general features of our Twitter application


  Scenario: Register
    Given I am on "http://localhost/test/index.php"
    Then I should see "Register"
    Then I follow "Register"
    And I should see "Registrieren :"
    And I should see "Email :"
    And I should see "Username :"
    And I should see "Passwort :"
    And I should see "Passwort erneut eingeben :"
    And I should see "Profilbild"
    And I should see "Registrieren"
    Then I fill in "Email" with "Behattest@behat.de"
    Then I fill in "regUsername" with "Behat"
    Then I fill in "regPassword" with "Behat"
    Then I fill in "regre-Password" with "Behat"
    Then I press "Registrieren"
    Then I should see "TwitterClone"

  Scenario: Login
    Given I am on "http://localhost/test/index.php"
    Then I should see "TwitterClone"
    And I should see "Register"
    And I should see "Username"
    And I should see "Password"
    And I should see "Login"
    Then I fill in "Username" with "Behat"
    Then I fill in "Password" with "Behat"
    Then I press "Login"
    Then I should see "Erfolgreich angemeldet!"
    And I should see "Optionen"
    And I should see "Angemeldet als : Behat"
    And I should see "Logout"

  Scenario: Test Mainpage
    Given I am on "http://localhost/test/index.php"
    Then I should see "TwitterClone"
    And I should see "Register"
    And I should see "Username"
    And I should see "Password"
    And I should see "Login"
    Then I fill in "Username" with "Behat"
    Then I fill in "Password" with "Behat"
    Then I press "Login"
    Then I should see "Erfolgreich angemeldet!"
    And I should see "Optionen"
    And I should see "Angemeldet als : Behat"
    And I should see "Logout"
    And I should see "Trends"
    And I should see "TWEETS"
    And I should see "FOLLOWING"
    And I should see "FOLLOWERS"
    And I should see "Vorgeschlagen"
    And I should see "Hier ist das Ende :("
    And I should see "Post"
    Then I fill in "Post" with "This is a Behat test"
    And I focus on Userinput
    Then I submit the field Userinput
    Then I should see "Tweet erfolgreich gepostet"

  Scenario: Test Logout
      Then I should see "Logout"
      And I press "Logout"
      Then I should not see "Logout"
      Given I am on "http://localhost/test/index.php"
      Then I should see "TwitterClone"
      And I should see "Register"
      And I should see "Username"
      And I should see "Password"
      And I should see "Login"
      Then I fill in "Username" with "Behat"
      Then I fill in "Password" with "Behat"
      Then I press "Login"
      Then I should see "Erfolgreich angemeldet!"
      And I should see "Optionen"
      And I should see "Angemeldet als : Behat"
      And I should see "Logout"
      Then I should see "Logout"

    Scenario: Post edit Test
      Given I am on "http://localhost/test/index.php"
      Then I should see "TwitterClone"
      And I should see "Register"
      And I should see "Username"
      And I should see "Password"
      And I should see "Login"
      Then I fill in "Username" with "Behat"
      Then I fill in "Password" with "Behat"
      Then I press "Login"
      Then I should see "Erfolgreich angemeldet!"
      And I should see "Optionen"
      And I should see "Angemeldet als : Behat"
      And I should see "Logout"
      And I should see "edit"
      And I follow "edit"
      And I should see "Edit"
      Then I focus on "Userinput"
      And I fill in "Userinput" with "Behat Edit"
      And I submit the field Userinput
      Then I should see "Eintrag erfolgreich geupdatet"

    Scenario: Post ReTweet Test
      Given I am on "http://localhost/test/index.php"
      Then I should see "TwitterClone"
      And I should see "Register"
      And I should see "Username"
      And I should see "Password"
      And I should see "Login"
      Then I fill in "Username" with "Behat"
      Then I fill in "Password" with "Behat"
      Then I press "Login"
      Then I should see "Erfolgreich angemeldet!"
      And I should see "Optionen"
      And I should see "Angemeldet als : Behat"
      And I should see "Logout"
      And I should see "ReTweet"
      And I follow "reTweet"
      And I should see "reTweet"
      Then I focus on "Userinput"
      And I fill in "Userinput" with "Behat reTweet"
      And I submit the field Userinput
      Then I should see "Tweet erfolgreich gepostet"

    Scenario: Post comment Test
      Given I am on "http://localhost/test/index.php"
      Then I should see "TwitterClone"
      And I should see "Register"
      And I should see "Username"
      And I should see "Password"
      And I should see "Login"
      Then I fill in "Username" with "Behat"
      Then I fill in "Password" with "Behat"
      Then I press "Login"
      Then I should see "Erfolgreich angemeldet!"
      And I should see "Optionen"
      And I should see "Angemeldet als : behat"
      And I should see "Logout"
      And I should see "comment"
      And I follow "comment"
      And I should see "commentinput"
      Then I focus on "commentinput"
      And I fill in "commentinput" with "Dies ist ein Behat test Kommentar"
      And I submit the field commentinput
      Then I should see "Kommentar erfolgreich gepostet"

    Scenario: CommentFeed test
      Given I am on "http://localhost/test/index.php"
      Then I should see "TwitterClone"
      And I should see "Register"
      And I should see "Username"
      And I should see "Password"
      And I should see "Login"
      Then I fill in "Username" with "Behat"
      Then I fill in "Password" with "Behat"
      Then I press "Login"
      Then I should see "Erfolgreich angemeldet!"
      And I should see "Optionen"
      And I should see "Angemeldet als : Behat"
      And I should see "Logout"
      And I should see "commentCounter"
      Then I follow "commentCounter"
      And I wait 4 seconds for request to complete
      And I should see "Userinput"
      And I wait 4 seconds for request to complete
      Then I fill in "Userinput" with "This is a Behat testComment from the commentFeed"
      And I focus on Userinput
      Then I submit the field Userinput
      Then I should see "Kommentar erfolgreich gepostet"
      And I should see "edit"
      And I follow "edit"
      Then I focus on "Userinput"
      And I fill in "Userinput" with "Behat Edit"
      And I submit the field Userinput
      Then I should see "Tweet erfolgreich gepostet"
      And I should see "delete"
      And I follow "delete"
      Then I should see "Tweet erfolgreich gelöscht"
      And I follow "Home"


    Scenario: Post delete Test
      Given I am on "http://localhost/test/index.php"
      Then I should see "TwitterClone"
      And I should see "Register"
      And I should see "Username"
      And I should see "Password"
      And I should see "Login"
      Then I fill in "Username" with "Behat"
      Then I fill in "Password" with "Behat"
      Then I press "Login"
      Then I should see "Erfolgreich angemeldet!"
      And I should see "Optionen"
      And I should see "Angemeldet als : Behat"
      And I should see "Logout"
      And I should see "delete"
      And I follow "delete"
      Then I should see "Tweet erfolgreich gelöscht"

    Scenario: Settings Test email
      Given I am on "http://localhost/test/index.php"
      Then I should see "TwitterClone"
      And I should see "Register"
      And I should see "Username"
      And I should see "Password"
      And I should see "Login"
      Then I fill in "Username" with "Behat"
      Then I fill in "Password" with "Behat"
      Then I press "Login"
      Then I should see "Erfolgreich angemeldet!"
      Then I should see "Optionen"
      And I press "Optionen"
      Then I should see "Einstellungen"
      And I follow "Einstellungen"
      Then I should see "Benutzerdaten Ändern"
      And I should see "email"
      And I should see "username"
      And I should see "password"
      And I should see "re-password"
      Then I fill in "email" with "Behat@behat2.de"
      Then I press "changeMail"
      Then I should see "erfolgreich geupdatet, bitte neu einloggen damit die änderung in kraft tritt"

    Scenario: Settings Test username
      Given I am on "http://localhost/test/index.php"
      Then I should see "TwitterClone"
      And I should see "Register"
      And I should see "Username"
      And I should see "Password"
      And I should see "Login"
      Then I fill in "Username" with "Behat"
      Then I fill in "Password" with "Behat"
      Then I press "Login"
      Then I should see "Erfolgreich angemeldet!"
      Then I should see "Optionen"
      And I press "Optionen"
      Then I should see "Einstellungen"
      And I follow "Einstellungen"
      Then I should see "Benutzerdaten Ändern"
      And I should see "email"
      And I should see "username"
      And I should see "password"
      And I should see "re-password"
      Then I fill in "username" with "Behat2"
      Then I press "change"
      Then I should see "erfolgreich geupdatet, bitte neu einloggen damit die änderung in kraft tritt"


    Scenario: Settings Test password
      Given I am on "http://localhost/test/index.php"
      Then I should see "TwitterClone"
      And I should see "Register"
      And I should see "Username"
      And I should see "Password"
      And I should see "Login"
      Then I fill in "Username" with "Behat2"
      Then I fill in "Password" with "Behat"
      Then I press "Login"
      Then I should see "Erfolgreich angemeldet!"
      Then I should see "Optionen"
      And I press "Optionen"
      Then I should see "Einstellungen"
      And I follow "Einstellungen"
      Then I should see "Benutzerdaten Ändern"
      And I should see "email"
      And I should see "username"
      And I should see "password"
      And I should see "re-password"
      Then I fill in "password" with "Behat2"
      Then I fill in "re-password" with "Behat2"
      Then I press "changePW"
      Then I should see "erfolgreich geupdatet, bitte neu einloggen damit die änderung in kraft tritt"


  Scenario: Delete Account
      Given I am on "http://localhost/test/index.php"
      Then I should see "TwitterClone"
      And I should see "Register"
      And I should see "Username"
      And I should see "Password"
      And I should see "Login"
      Then I fill in "Username" with "Behat2"
      Then I fill in "Password" with "Behat2"
      Then I press "Login"
      Then I should see "Erfolgreich angemeldet!"
      And I should see "Angemeldet als : Behat"
      And I should see "Logout"
      Then I should see "Optionen"
      And I press "Optionen"
      Then I should see "Account Löschen"
      Then I follow "Account Löschen"
      Then I should see "Register"