Feature: General Test of Twitter application
  This Feature tests the general features of our Twitter application


  Scenario: Register
    Given I am on "http://localhost/test/index.php"
    Then I should see "Register"
    Then I follow "Register"
    And I should see "Registrieren :"
    And I should see "Email :"
    And I should see "Username :"
    And I should see "Passwort :"
    And I should see "Passwort erneut eingeben :"
    And I should see "Profilbild"
    And I should see "Registrieren"
    Then I fill in "Email" with "Behattest@behat.de"
    Then I fill in "Username" with "Behat"
    Then I fill in "Password" with "Behat"
    Then I fill in "re-Password" with "Behat"
    Then I press "Registrieren"
    Then I should see "TwitterClone"

  Scenario: Login
    Given I am on "http://localhost/test/index.php"
    Then I should see "TwitterClone"
    And I should see "Register"
    And I should see "Username"
    And I should see "Password"
    And I should see "Login"
    Then I fill in "Username" with "Behat"
    Then I fill in "Password" with "Behat"
    Then I press "Login"
    Then I should see "Erfolgreich angemeldet!"
    And I should see "Optionen"
    And I should see "Angemeldet als : Behat"
    And I should see "Logout"

  Scenario: Test Mainpage
    Given I am on "http://localhost/test/index.php"
    Then I should see "TwitterClone"
    And I should see "Register"
    And I should see "Username"
    And I should see "Password"
    And I should see "Login"
    Then I fill in "Username" with "Behat"
    Then I fill in "Password" with "Behat"
    Then I press "Login"
    Then I should see "Erfolgreich angemeldet!"
    And I should see "Optionen"
    And I should see "Angemeldet als : Behat"
    And I should see "Logout"
    And I should see "Trends"
    And I should see "TWEETS"
    And I should see "FOLLOWING"
    And I should see "FOLLOWERS"
    And I should see "Vorgeschlagen"
    And I should see "Hier ist das Ende :("
    And I should see "Post"
    Then I fill in "Post" with "This is a Behat test"
    And I focus on Userinput
    Then I submit the field Userinput
    Then I should see "Tweet erfolgreich gepostet"

  Scenario: Test Logout
      Then I should see "Logout"
      And I press "Logout"
      Then I should not see "Logout"
      Given I am on "http://localhost/test/index.php"
      Then I should see "TwitterClone"
      And I should see "Register"
      And I should see "Username"
      And I should see "Password"
      And I should see "Login"
      Then I fill in "Username" with "Behat"
      Then I fill in "Password" with "Behat"
      Then I press "Login"
      Then I should see "Erfolgreich angemeldet!"
      And I should see "Optionen"
      And I should see "Angemeldet als : Behat"
      And I should see "Logout"
      Then I should see "Logout"

    Scenario: Post edit Test
      Given I am on "http://localhost/test/index.php"
      Then I should see "TwitterClone"
      And I should see "Register"
      And I should see "Username"
      And I should see "Password"
      And I should see "Login"
      Then I fill in "Username" with "Behat"
      Then I fill in "Password" with "Behat"
      Then I press "Login"
      Then I should see "Erfolgreich angemeldet!"
      And I should see "Optionen"
      And I should see "Angemeldet als : Behat"
      And I should see "Logout"
      

    Scenario: Delete Account
      Given I am on "http://localhost/test/index.php"
      Then I should see "TwitterClone"
      And I should see "Register"
      And I should see "Username"
      And I should see "Password"
      And I should see "Login"
      Then I fill in "Username" with "Behat"
      Then I fill in "Password" with "Behat"
      Then I press "Login"
      Then I should see "Erfolgreich angemeldet!"
      And I should see "Optionen"
      And I should see "Angemeldet als : Behat"
      And I should see "Logout"
      Then I should see "Optionen"
      And I press "Optionen"
      Then I should see "Account Löschen"
      Then I follow "Account Löschen"
      Then I should see "Register"